### ISSUE TITLE
Chef 12 depends on Ohai 8 which requires ruby 2.0

### ISSUE THREAD

**Issue by mistakia** [bmuller/toquen#4]
Running ([in the ubuntu_bootstrap](https://github.com/bmuller/toquen/blob/master/lib/toquen/templates/ubuntu_bootstrap.erb#L14))

```
gem install --no-rdoc --no-ri chef
```

causes the following error:

```
Error installing chef:
ohai requires Ruby version >= 2.0.0.
```

How do you want to handle this in the bootstrap? Shall we pin chef to version 11.16.4 or install ruby >2.0?

https://github.com/opscode/chef/issues/2517

**Comment by bmuller** [comment]
Install ruby 2.0 in the ubuntu_bootstrap script I think.  Can you try and see if it works?

**Comment by vacay** [comment]
I sure can - will update soon with a pull request.
